### ISSUE TITLE
Empty dump

### ISSUE THREAD

**Issue by danilopaulinodasilva** [usolved/mysql-backup-to-ftp#1]
I've tried to use the script, uploads fine. But, returns me a empty dump .sql file, i miss some configuration? And I was thinking there is no need info the database server?

**Comment by usolved** [comment]
Yes there's no need for the database server because the script is running on the same server as the mysql database (at least as the script is working right now).

Did you check if it's allowed to use PHP exec on your server to execute shell commands?


Does it work when you try the mysqldump command on the command line without the PHP script?

`mysqldump -u youruser -pyourpassword --allow-keywords --add-drop-table --complete-insert --hex-blob --quote-names yourdbname > backupfile.sql`

(make sure there's _no_ space between argument -p and your password)

If this will work out for you and you're using the same account and db info in the PHP script and execution of shell commands is allowed it should be working.

**Comment by danilopaulinodasilva** [comment]
Oh, great!

I made the question because I was looking for something different in general. But maybe is my hosting server who are blocking the commands via exec on PHP.

Anyway I wrote a code, compiling some others code to do the job 100% via PHP script instead doing exec on PHP or cron commands.

I'll try your code in a dedicated server instead a shared for tests, thanks anyway.

Best regards,
